# Default values for ghr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "iehprdacr0120.azurecr.io/aks-github-runner"
  pullPolicy: IfNotPresent
  tag: "0.0.14"

ingress:
  enabled: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: true

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "1Gi"
    cpu: "1"
    ephemeral-storage: '20Gi'
  limits:
    memory: "2Gi"
    cpu: "2"
    ephemeral-storage: '40Gi'

ghr:
  repo_owner: "InExtenso"
  repo_name: "aks-github-runner"
  repo_url: "https://github.com/InExtenso"
  github_token: "CHANGETHIS"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
