# This workflow creates a self-hosted Github Runner on AKS
name: AKS Self Hosted Runner

on: workflow_dispatch

env:
  RESOURCE_GROUP_NAME: ${{ vars.AKS_RG_PROD }}
  CLUSTER_NAME: ${{ vars.AKS_CLUSTER_NAME_PROD }}
  ACR_NAME: ${{ vars.ACR_LOGIN_SERVER }}
  GH_TOKEN: ${{ secrets.GH_TOKEN_AKS_RUNNER }}
  HELM_EXPERIMENTAL_OCI: 1
  
jobs:
  build:
#    Use github public runners
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Github Runner image
        run: |
          az configure --defaults acr=${ACR_NAME}
          az acr build -t ghrunner:${GITHUB_SHA} ./ghrdocker

      - name: Create Helm chart
        run: |
          # az configure --defaults acr=${ACR_NAME}
          # az acr login -n ${CLUSTER_NAME}
          cd ./ghrhelm
          helm package .
          # helm push ghr-0.0.1.tgz oci://${ACR_NAME}.azurecr.io/ghrunner

      - name: AKS set context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.RESOURCE_GROUP_NAME }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy via Helm
        run: |
          cd ./ghrhelm
          # az configure --defaults acr=${ACR_NAME}
          # helm pull oci://${ACR_NAME}.azurecr.io/ghrunner/ghr --version 0.0.1
          helm install ghrunner ghr-0.0.1.tgz \
            --set image.repository=${ACR_NAME}.azurecr.io/ghrunner \
            --set image.tag=${GITHUB_SHA} \
            --set ghr.github_token=${GH_TOKEN}