# This workflow creates a self-hosted Github Runner on AKS
name: AKS Self Hosted Runner

on:
  workflow_dispatch:
    inputs:
      min-runners:
        description: 'Minimum runners'
        required: true
        type: choice
        options: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10' ]
        default: '1'
      max-runners:
        description: 'Maximum runners'
        required: true
        type: choice
        options: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10' ]
        default: '3'

env:
  RESOURCE_GROUP_NAME: ${{ vars.AKS_RG_PROD }}
  CLUSTER_NAME: ${{ vars.AKS_CLUSTER_NAME_PROD }}
  AZ_CRENDENTIALS: ${{secrets.AZURE_CREDENTIALS_PROD}}
  ACR_NAME: ${{ vars.ACR_LOGIN_SERVER }}
  GH_TOKEN: ${{ secrets.GH_TOKEN_AKS_RUNNER }}
  HELM_EXPERIMENTAL_OCI: 1
  ACR_SUBSCRIPTION_ID: ${{vars.ACR_SUBSCRIPTION_ID}}

jobs:
  build:
    name:
#    Use github public runners
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v2.1.1
        with:
          creds: ${{ env.AZ_CRENDENTIALS }}

      - name: Build and push Github Runner image
        run: |
          az account set --subscription ${ACR_SUBSCRIPTION_ID}
          az configure --defaults acr=${ACR_RG}/${ACR_NAME}
          az acr build -t ghrunner:${GITHUB_SHA} ./ghrdocker

      - name: Create Helm chart
        run: |
          # az configure --defaults acr=${ACR_NAME}
          # az acr login -n ${CLUSTER_NAME}
          cd ./ghrhelm
          helm package .
          # helm push ghr-0.0.1.tgz oci://${ACR_NAME}.azurecr.io/ghrunner

      - name: AKS set context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ env.AZ_CRENDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP_NAME }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy via Helm
        run: |
          cd ./ghrhelm
          # az configure --defaults acr=${ACR_NAME}
          # helm pull oci://${ACR_NAME}.azurecr.io/ghrunner/ghr --version 0.0.1
          helm install ghrunner ghr-0.0.1.tgz \
            --set image.repository=${ACR_NAME}.azurecr.io/ghrunner \
            --set image.tag=${GITHUB_SHA} \
            --set ghr.github_token=${GH_TOKEN} \
            --set replicaCount=${github.event.inputs.min-runners} \
            --set autoscaling.minReplicas=${github.event.inputs.min-runners} \
            --set autoscaling.maxReplicas=${github.event.inputs.max-runners} \
            --namespace==githubhostedrunner
